cart/urls.py
from django.urls import path
from .views import cart_add, cart_list, cart_checkout

app_name = 'cart'

urlpatterns = [
    path('cart_add/<str:action>-<int:pid>/', cart_add, name="cart_add"),
    path('cart/', cart_list, name="cart"),
    path('buyurtma/', cart_checkout, name="buyurtma")
]

internetdokon/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from account.models import User
from internetdokon.validators import PhoneValidator
from main.models import Product


class Order(models.Model):
    STATUS_YES = 1
    STATUS_NO = 0

    PAYMENT_STATUS_NEW = 0
    PAYMENT_STATUS_PREPARE = 1
    PAYMENT_STATUS_COMPLETE = 2

    user = models.ForeignKey(User, on_delete=models.RESTRICT)
    address = models.TextField()
    phone = models.CharField(max_length=16, validators=[PhoneValidator()])
    zip_code = models.CharField(max_length=20)
    status = models.SmallIntegerField(choices=(
        (STATUS_YES, "Bor"),
        (STATUS_NO, "Yo'q")
    ))

    payment_status = models.SmallIntegerField(choices=(
        (PAYMENT_STATUS_NEW, "New"),
        (PAYMENT_STATUS_PREPARE, "Prepare"),
        (PAYMENT_STATUS_COMPLETE, "Complete"),
    ), default=PAYMENT_STATUS_NEW)
    order_at = models.DateTimeField(auto_now_add=True)


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.RESTRICT)
    product = models.ForeignKey(Product, on_delete=models.RESTRICT)
    amount = models.IntegerField()

cart/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('address', 'phone', 'zip_code')

cart/views.py
from django.db import transaction
from django.db.models import F
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from cart.forms import OrderForm
from cart.models import Order, OrderProduct
from main.models import Product


def cart_add(request, pid, action):
    product = Product.objects.get(id=pid)
    pid = str(product.id)

    cart = request.session.get('cart', {})

    if cart is None:
        cart = {}

    if action == 'inc':
        cart[pid] = min(cart.get(pid, 0) + 1, product.available)

    elif action == 'dec':
        cart[pid] = max(cart.get(pid, 0) - 1, 0)

    if cart[pid] == 0:
        del cart[pid]

    print(cart)

    request.session['cart'] = cart

    return redirect('main:product_info', product.id)


def cart_list(request):
    cart = request.session.get('cart', {})
    if not cart:
        return redirect('main:index')

    products = Product.objects.filter(id__in=cart.keys()).all()
    result = [{
        'p': row,
        'n': cart[str(row.id)],
        'total': cart[str(row.id)] * row.price
    } for row in products]

    return render(request, 'cart/karzinka_info.html', {
        'list': result,

        'total': sum([row['total'] for row in result])
    })

@login_required
def cart_checkout(request):
    cart = request.session.get('cart', {})
    if not cart:
        return redirect('main:index')

    products = Product.objects.filter(id__in=cart.keys()).all()
    result = [{
        'p': row,
        'n': cart[str(row.id)],
        'total': cart[str(row.id)] * row.price
    } for row in products]

    form = OrderForm()
    if request.method == 'POST':
        form = OrderForm(data=request.POST)
        if form.is_valid():
            with transaction.atomic():
                form.instance.status = Order.STATUS_YES
                form.instance.user = request.user
                order = form.save()

                products = []
                for pid, n in cart.items():
                    k = Product.objects.filter(id=pid, available__gte=n).update(available=F("available") - n)
                    if not k:
                        raise Exception(f"Mahsulot qolamdi {pid}={n}")
                    products.append(OrderProduct(order=order, product_id=pid, amount=n))

                OrderProduct.objects.bulk_create(products)

                request.session['cart'] = {}

                return redirect('main:index')

    return render(request, 'cart/buyurtma.html', {
        'form': form,
        'products': result

    })

templates/cart/buyurtma.html
{% extends 'layouts/base.html' %}
{% load static crispy_forms_filters %}
{% block content %}

    <div class="container mt-3">
        <form method="post" action="">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success">Yuborish</button>
        </form>
    </div>
    <br/>
    <br/>
{% endblock %}

templates/cart/karzinka_info.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="container mt-3">
    <table class="table table-bordered table-hover table-striped">
        <thead>
        <tr>
            <th>Mahsulot</th>
            <th>Soni</th>
            <th>Narxi</th>Mongodb,
            <th>Jami</th>
        </tr>
        </thead>
        <tbody>
        {% for row in list %}
        <tr>
        <td>{{ row.p.name }}</td>
        <td>{{ row.n }}</td>
        <td>${{ row.p.price }}</td>
        <td>${{ row.total }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <h2 class="text-primary">Umumiy summa: ${{ total }}</h2>
    <hr/>
    {% if user.is_authenticated %}
        <a href="{% url 'cart:buyurtma' %}" class="btn btn-info">Malumotlaringizni kiriting</a><br/><br/><br/><br/>
        {% else %}
        <a href="#" class="btn btn-info">Registratsiya</a>
    {% endif %}
    </div>
{% endblock %}