cart/urls.py
from django.urls import path
from .views import cart_add, cart_list, cart_checkout

app_name = 'cart'

urlpatterns = [
    path('cart_add/<str:action>-<int:pid>/', cart_add, name="cart_add"),
    path('cart/', cart_list, name="cart"),
    path('buyurtma/', cart_checkout, name="buyurtma")
]

internetdokon/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import About_main, Index_main, Testimonial_main, Why_main, ProductWiew


from .views import ProductInfo


app_name = 'main'

urlpatterns = [
    path('', Index_main, name="index"),
    path('about/', About_main.as_view(), name="about"),
    path('product/', ProductWiew.as_view(), name="product"),
    path('test/', Testimonial_main.as_view(), name="test"),
    path('why/', Why_main.as_view(), name="why"),

    path('product_info-<int:pk>/', ProductInfo.as_view(), name="product_info"),
]

main/models.py
from django.db import models
from account.models import User
from common.models import Country, Region, District
from internetdokon.validators import PhoneValidator


class Carusel(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField()
    content = models.TextField()


class Product(models.Model):
    STATUS_YES = 1
    STATUS_NO = 0
    name = models.CharField(max_length=100)
    image = models.ImageField()
    price = models.IntegerField()
    available = models.IntegerField(default=0)
    sold = models.IntegerField(default=0)
    status = models.SmallIntegerField(choices=(
        (STATUS_YES, "Bor"),
        (STATUS_NO, "Qolmagan")
    ))

    def __str__(self):
        return self.name

    class Meta:
        indexes = (
            models.Index(fields=('status',)),
        )

main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic import DetailView
from django_filters.views import FilterView

from main.filters import ProductFilter
from main.models import Product


def Index_main(request):
    q = request.GET.get('q', '')
    queryset = Product.objects.order_by('-id').all()
    if q is not None:
        queryset = queryset.filter(name__icontains=q)

    return render(request, 'main/index.html', {
        'products': queryset,
        'q': q
    })

    # template_name = 'main/index.html'
    # filterset_class = ProductFilter

    # def get_context_data(self, **kwargs):
    #
    #     context = super().get_context_data(**kwargs)
    #     context['products'] = Product.objects.order_by('-id').all()
    #     return context


class About_main(TemplateView):
     template_name = 'main/about.html'


class ProductWiew(FilterView):
    template_name = 'main/product.html'
    filterset_class = ProductFilter


class ProductInfo(DetailView):
    model = Product
    template_name = 'main/product_info.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        cart = self.request.session.get('cart')
        pid = str(self.object.id)
        context['cart_p'] = cart[pid] if cart and pid in cart else 0
        return context


class Testimonial_main(TemplateView):
    template_name = 'main/testimonial.html'


class Why_main(TemplateView):
    template_name = 'main/why.html'

templates/main/about.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
<head>
  <!-- Basic -->

  <!-- bootstrap core css -->

</head>

<body class="sub_page">

  <div class="hero_area">
    <!-- header section strats -->
    <!-- end header section -->
  </div>

  <!-- about section -->

  <section class="about_section">
    <div class="container-fluid  ">
      <div class="row">
        <div class="col-md-5 ml-auto">
          <div class="detail-box pr-md-3">
            <div class="heading_container">
              <h2>
                We Provide Best For You
              </h2>
            </div>
            <p>
              Totam architecto rem beatae veniam, cum officiis adipisci soluta perspiciatis ipsa, expedita maiores quae accusantium. Animi veniam aperiam, necessitatibus mollitia ipsum id optio ipsa odio ab facilis sit labore officia!
              Repellat expedita, deserunt eum soluta rem culpa. Aut, necessitatibus cumque. Voluptas consequuntur vitae aperiam animi sint earum, ex unde cupiditate, molestias dolore quos quas possimus eveniet facilis magnam? Vero, dicta.
            </p>
            <a href="">
              Read More
            </a>
          </div>
        </div>
        <div class="col-md-6 px-0">
          <div class="img-box">
            <img src="../../assets/images/about-img.jpg" alt="">
          </div>
        </div>
      </div>
    </div>
  </section>


  <!-- end about section -->

  <!-- info section -->

  <!-- end info_section -->


  <!-- footer section -->
  <footer class="footer_section">
    <div class="container">
      <p>
        &copy; <span id="displayYear"></span> All Rights Reserved By
        <a href="https://html.design/">Free Html Templates</a>
      </p>
    </div>
  </footer>
  <!-- footer section -->

  <!-- jQery -->
  <script src="../../assets/js/jquery-3.4.1.min.js"></script>
  <!-- bootstrap js -->
  <script src="../../assets/js/bootstrap.js"></script>
  <!-- custom js -->
  <script src="../../assets/js/custom.js"></script>


</body>

</html>

{% endblock %}

templates/main/product.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}

    <section class="product_section layout_padding">
        <div class="container-fluid">

            <div class="row">
                <div class="col-lg-3 col-xl-2">
                    <form method="get">
                        {{ filter.form.as_p }}
                        <button class="btn btn-danger" type="submit">Filter</button>
                    </form>
                </div>
            </div>

            <div class="container">
                <div class="row">
                    {% for p in object_list %}
                        <div class="col-sm-9 col-lg-4">
                            <div class="box"><h4>{{ p.name }}</h4>
                                <div class="img-box">
                                    <img src="{{ p.image.url }}">
                                </div>
                                <div class="detail-box">
                                    <h5>
                                        <p>Narxi: $ {{ p.price }}</p>
                                        <a href="{% url 'main:product_info' p.id %}" class="text-primary">Batafsil
                                            Ma'lumot</a>
                                        <br/>
                                    </h5>
                                </div>
                            </div>
                        </div>
                    {% empty %}
                        <div class="col-12">
                        <h2>Birorta ham mahsulot topilmadi Janob</h2>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/main/product_info.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="container mt-3">
        <h1 class="text-primary">{{ object.name }}</h1>
        <div class="text-center">
            <img src="{{ product.image.url }}">
        </div>
        <h3 class="text-primary">Narxi: ${{ product.price }}</h3><br/>

        {% if object.available > 0 %}
            {% if cart_p > 0 %}
                <a href="{% url 'cart:cart_add' 'dec' object.id %}" class="btn btn-info mb-3">-</a>
                <span>{{ cart_p }}</span>
                <a href="{% url 'cart:cart_add' 'inc' object.id %}" class="btn btn-info mb-3">+</a><br/>

                {% else %}
                <a href="{% url 'cart:cart_add' 'inc' object.id %}" class="btn btn-info mb-3">Buyurtma berish</a><br/>
                {% endif %}
        {% endif %}

        {% lorem 2 %}
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    </div>
{% endblock %}

templates/main/testimonial.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <link rel="icon" href="{% static "images/fevicon.png" %}" type="image/gif" />
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />



  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet"> <!-- range slider -->

  <!-- font awesome style -->
  <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static "css/style.css" %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static "css/responsive.css" %}" rel="stylesheet" />

</head>

<body class="sub_page">

  <div class="hero_area">
    <!-- header section strats -->

    <!-- end header section -->
  </div>



  <!-- client section -->

  <section class="client_section layout_padding">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
          What Says Our Customers
        </h2>
      </div>
    </div>
    <div class="client_container ">
      <div id="carouselExample2Controls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="container">
              <div class="box">
                <div class="detail-box">
                  <p>
                    <i class="fa fa-quote-left" aria-hidden="true"></i>
                  </p>
                  <p>
                    It is a long established fact that a reader will be distracted by the readable content of a page
                    when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal
                    distribution of letters, as opposed to using 'Content here, content here', making it lookIt is a
                    long established fact that a reader will be distracted by the readable content of a page when
                    looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal
                    distribution of letters, as opposed to using 'Content here, content here', making it look
                  </p>
                </div>
                <div class="col-lg-4">
                <div class="client-id">
                  <div class="img-box">
                    <img src="{% static "images/client.jpg" %}" alt="">
                  </div>
                  <div class="name">
                </div>
                    <h5>
                      Jek Uilmas [devoloper]
                    </h5>
                    <h6>

                    </h6>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>


</body>

</html>

{% endblock %}

templates/main/why.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <link rel="icon" href="{% static "images/fevicon.png" %}" type="image/gif" />
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />


  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet"> <!-- range slider -->


</head>

<body class="sub_page">

  <div class="hero_area">
    <!-- header section strats -->

    <!-- end header section -->
  </div>

  <!-- why us section -->

  <section class="why_us_section layout_padding">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
          Why Choose Us
        </h2>
      </div>
      <div class="row">
        <div class="col-md-4">
          <div class="box ">
            <div class="img-box">
              <img src="{% static "images/w1.png" %}" alt="">
            </div>
            <div class="detail-box">
              <h5>
                Fast Delivery
              </h5>
              <p>
                variations of passages of Lorem Ipsum available
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="box ">
            <div class="img-box">
              <img src="{% static "images/w2.png" %}" alt="">
            </div>
            <div class="detail-box">
              <h5>
                Free Shiping
              </h5>
              <p>
                variations of passages of Lorem Ipsum available
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="box ">
            <div class="img-box">
              <img src="{% static "images/w3.png" %}" alt="">
            </div>
            <div class="detail-box">
              <h5>
                Best Quality
              </h5>
              <p>
                variations of passages of Lorem Ipsum available
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end why us section -->

  <!-- info section -->
  <!-- end info_section -->


  <!-- footer section -->
  <footer class="footer_section">
    <div class="container">
      <p>
        &copy; <span id="displayYear"></span> All Rights Reserved By
        <a href="https://html.design/">Free Html Templates</a>
      </p>
    </div>
  </footer>


{% endblock %}