account/urls.py
from django.urls import path
from .views import RegistrationView, LoginView, LogautView

app_name = 'account'


urlpatterns = [
    path('registration/', RegistrationView, name="registration"),
    path('login/', LoginView, name="login"),
    path('logout/', LogautView, name="logout")
]

cart/urls.py
from django.urls import path
from .views import cart_add, cart_list, cart_checkout

app_name = 'cart'

urlpatterns = [
    path('cart_add/<str:action>-<int:pid>/', cart_add, name="cart_add"),
    path('cart/', cart_list, name="cart"),
    path('buyurtma/', cart_checkout, name="buyurtma")
]

internetdokon/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('account/', include('account.urls')),
    path('cart/', include('cart.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layouts/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>InternetDokon</title>

    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'vendor/bootstrap-icons.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}" />


  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet"> <!-- range slider -->

  <!-- font awesome style -->
  <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static "css/style.css" %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static "css/responsive.css" %}" rel="stylesheet" />


</head>
<body>

    <header class="header_section">
      <div class="header_top">
        <div class="container-fluid">
          <div class="top_nav_container">
            <div class="contact_nav">
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Call : +99894 623 94 55
                </span>
              </a>
              <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  Email : demo@gmail.com
                </span>
              </a>
            </div>
            <form method="get" class="d-flex">
                <input type="text" name="q" placeholder="Qidirish" value="{{ q }}" class="form-control">
                <button type="submit" class="btn btn-success bi bi-search"></button>
            </form>
            <div class="user_option_box">
              <a href="{% url 'account:registration' %}" class="account-link">
                <i class="fa fa-user" aria-hidden="true"></i>
                <span>
                    Avtorizatsiya
                </span>
              </a>

                {% if user.is_authenticated %}
                <a href="{% url 'account:logout' %}" class="account-link">
                <i class="fa fa-user" aria-hidden="true"></i>
                <span>
                    {{ user }}
                </span>
                </a>
                {% else %}
                <a href="{% url 'account:login' %}" class="account-link">
                <i class="fa fa-user" aria-hidden="true"></i>
                <span>
                    Login
                </span>
                </a>
                {% endif %}


              <a href="{% url 'cart:cart' %}" class="cart-link">
                <i class="fa fa-shopping-cart" aria-hidden="true">{{ cart_n }}</i>
                <span>
                    Karzinka
                </span>
              </a>
            </div>
          </div>

        </div>
      </div>
      <div class="header_bottom">
        <div class="container-fluid">
          <nav class="navbar navbar-expand-lg custom_nav-container ">
            <a class="navbar-brand" href="index.html">
              <span>
                Minics
              </span>
            </a>


            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ">
                <li class="nav-item dropdown">
                  <a class="nav-link{% if request.resolver_match.url_name == 'main:index' %} active{% endif %}" href="{% url "main:index" %}">Bosh sahifa<span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item dropdown">
                  <a class="nav-link{% if request.resolver_match.url_name == 'main:product' %} active{% endif %}" href="{% url "main:product" %}">Mahsulot</a>
                </li>

                <li class="nav-item dropdown">
                  <a class="nav-link{% if request.resolver_match.url_name == 'main:about' %} active{% endif %}" href="{% url "main:about" %}">Biz haqimizda</a>
                </li>

                <li class="nav-item dropdown">
                  <a class="nav-link{% if request.resolver_match.url_name == 'main:why' %} active{% endif %}" href="{% url "main:why" %}">Nega biz</a>
                </li>

                <li class="nav-item dropdown">
                  <a class="nav-link{% if request.resolver_match.url_name == 'main:test' %} active{% endif %}" href="{% url "main:test" %}">Kammentariya</a>
                </li>
              </ul>
            </div>

          </nav>
        </div>
      </div>
    </header>

<div class="container">
    {% for m in messages %}
        <div class="alert {{ m.tags }}">{{ m }}</div>
    {% endfor %}
</div>
{% block content %}{% endblock %}

 <section class="info_section ">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <div class="info_contact">
            <h5>
              <a href="" class="navbar-brand">
                <span>
                  Minics
                </span>
              </a>
            </h5>
            <p>
              <i class="fa fa-map-marker" aria-hidden="true"></i>
              Address
            </p>
            <p>
              <i class="fa fa-phone" aria-hidden="true"></i>
              +01 1234567890
            </p>
            <p>
              <i class="fa fa-envelope" aria-hidden="true"></i>
              demo@gmail.com
            </p>
          </div>
        </div>
        <div class="col-md-3">
          <div class="info_info">
            <h5>
              Information
            </h5>
            <p>
              Eligendi sunt, provident, debitis nemo, facilis cupiditate velit libero dolorum aperiam enim nulla iste maxime corrupti ad illo libero minus.
            </p>
          </div>
        </div>
        <div class="col-md-3">
          <div class="info_links">

          </div>
        </div>
        <div class="col-md-3">
          <div class="info_form ">
            <h5>
              Newsletter
            </h5>
            <form action="">
              <input type="email" placeholder="Enter your email">
              <button>
                Subscribe
              </button>
            </form>
            <div class="social_box">
              <a href="">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-youtube" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
<script rel="{% static 'vendor/bootstrap/js/bootstrap.bundle.js' %}"></script>

</body>
</html>